In [2]:
import pandas as pd
import numpy as np

In [3]:
path = r'E:\E-commerce Analysis\Data\raw\perfil_cliente.csv'
df = pd.read_csv(path, sep=';', encoding='cp1252')

In [4]:
df.head()

,customer_id,total_gasto,numero_pedidos,flag_cliente
0,15f3f60c0575a9f2a7d5434f7b8a7692,60.849998,1,Não recorrente
1,5a3f73cc3e52ab64478beb5ce8756f4b,413.309998,1,Não recorrente
2,d68f9c633f9ab44265b54f3792fcbe71,93.800003,1,Não recorrente
3,454b89aa74cc3a41ac6a964e7f6c9e67,147.610001,1,Não recorrente
4,5a23a92261328e087c062a7c265b7862,137.000000,1,Não recorrente

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     99441 non-null  str
 1   total_gasto     99441 non-null  float64
 2   numero_pedidos  99441 non-null  int64
 3   flag_cliente    99441 non-null  str
dtypes: float64(1), int64(1), str(2)
memory usage: 3.0 MB

In [6]:
df.isnull().sum()

customer_id       0
total_gasto       0
numero_pedidos    0
flag_cliente      0
dtype: int64

In [7]:
df['total_gasto'] = df['total_gasto'].replace(',', '.')
df['total_gasto'] = df['total_gasto'].round(2)

In [8]:
df.head()

,customer_id,total_gasto,numero_pedidos,flag_cliente
0,15f3f60c0575a9f2a7d5434f7b8a7692,60.85,1,Não recorrente
1,5a3f73cc3e52ab64478beb5ce8756f4b,413.31,1,Não recorrente
2,d68f9c633f9ab44265b54f3792fcbe71,93.80,1,Não recorrente
3,454b89aa74cc3a41ac6a964e7f6c9e67,147.61,1,Não recorrente
4,5a23a92261328e087c062a7c265b7862,137.00,1,Não recorrente

In [13]:
#Quantos clientes compraram mais de 1 vez
clientes_fieis = df[df['numero_pedidos'] > 1]
print(f'Número de clientes fiéis: {clientes_fieis.shape[0]}')

Número de clientes fiéis: 9803

In [14]:
#Quantidade Cliente não recorrentes
clientes_nao_fieis = df[df['numero_pedidos'] == 1]
print(f'Número de clientes não fiéis: {clientes_nao_fieis.shape[0]}')

Número de clientes não fiéis: 89638

In [15]:
#Taxa de recorrencia
taxa_recorrencia = (clientes_fieis.shape[0] / df.shape[0]) * 100
print(f'Taxa de recorrência: {taxa_recorrencia:.2f}%')

Taxa de recorrência: 9.86%