In [2]:
import pandas as pd
import numpy as np

In [3]:
path = r'E:\E-commerce Analysis\Data\processed\perfil_cliente_tratada.csv'
df = pd.read_csv(path, sep=';', encoding='cp1252')

In [4]:
df.head()

,customer_unique_id,quantidade_vendida,total_gasto,flag_cliente
0,ea046dbb36d4b15b577065b530a08ec3,1,69.320000,Não recorrente
1,67d21c8bea9d6017d1b124d3879dd815,1,133.279999,Não recorrente
2,dcfbc32ae520bb179c3dd7a85d305452,1,116.940002,Não recorrente
3,fc19fe9ac733e36ff8227c29435c2030,2,133.529997,Recorrente
4,b4b26faae91bc1b8f9458d29bc3c200c,1,143.039993,Não recorrente

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 96096 entries, 0 to 96095
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_unique_id  96096 non-null  str
 1   quantidade_vendida  96096 non-null  int64
 2   total_gasto         96096 non-null  float64
 3   flag_cliente        96096 non-null  str
dtypes: float64(1), int64(1), str(2)
memory usage: 2.9 MB

In [6]:
df.isnull().sum()

customer_unique_id    0
quantidade_vendida    0
total_gasto           0
flag_cliente          0
dtype: int64

In [7]:
df['total_gasto'] = df['total_gasto'].replace(',', '.')
df['total_gasto'] = df['total_gasto'].round(2)

In [8]:
df.head()

,customer_unique_id,quantidade_vendida,total_gasto,flag_cliente
0,ea046dbb36d4b15b577065b530a08ec3,1,69.32,Não recorrente
1,67d21c8bea9d6017d1b124d3879dd815,1,133.28,Não recorrente
2,dcfbc32ae520bb179c3dd7a85d305452,1,116.94,Não recorrente
3,fc19fe9ac733e36ff8227c29435c2030,2,133.53,Recorrente
4,b4b26faae91bc1b8f9458d29bc3c200c,1,143.04,Não recorrente

In [9]:
#Quantos clientes compraram mais de 1 vez
clientes_fieis = df[df['quantidade_vendida'] > 1]
print(f'Número de clientes fiéis: {clientes_fieis.shape[0]}')

Número de clientes fiéis: 2997

In [10]:
#Quantidade Cliente não recorrentes
clientes_nao_fieis = df[df['quantidade_vendida'] == 1]
print(f'Número de clientes não fiéis: {clientes_nao_fieis.shape[0]}')

Número de clientes não fiéis: 93099

In [11]:
#Taxa de recorrencia
taxa_recorrencia = (clientes_fieis.shape[0] / df.shape[0]) * 100
print(f'Taxa de recorrência: {taxa_recorrencia:.2f}%')

Taxa de recorrência: 3.12%

In [12]:
#Taxan de Churn
taxa_churn = (clientes_nao_fieis.shape[0] / df.shape[0]) * 100
print(f'Taxa de churn: {taxa_churn:.2f}%')

Taxa de churn: 96.88%