In [1]:
import pandas as pd

In [2]:
path = r'E:\E-commerce Analysis\Data\raw\performance_produto.csv'

In [3]:
df = pd.read_csv(path, sep=';')

In [10]:
df.head()

    product_category_name  quantidade_vendida  receita_total
0      relogios_presentes                5991   1,429,216.68
1  informatica_acessorios                7827   1,585,330.45
2      ferramentas_jardim                4347     838,280.75
3              perfumaria                3419     506,738.66
4           esporte_lazer                8641   1,392,127.56

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   product_category_name  73 non-null     str
 1   quantidade_vendida     74 non-null     int64
 2   receita_total          74 non-null     float64
dtypes: float64(1), int64(1), str(1)
memory usage: 1.9 KB

In [11]:
pd.options.display.float_format = '{:,.2f}'.format

In [16]:
df.isnull().sum()

product_category_name    0
quantidade_vendida       0
receita_total            0
dtype: int64

In [15]:
df[(df['product_category_name'].isnull())]

Empty DataFrame
Columns: [product_category_name, quantidade_vendida, receita_total]
Index: []

In [14]:
df['product_category_name'] = df['product_category_name'].fillna('Unknown')