In [1]:
import pandas as pd

In [2]:
path = r'E:\E-commerce Analysis\Data\raw\vendas_mensais.csv'

In [3]:
df = pd.read_csv(path, sep=';')

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ano                 25 non-null     int64
 1   mes                 25 non-null     int64
 2   quantidade_pedidos  25 non-null     int64
 3   faturamento         25 non-null     float64
 4   ticket_medio        25 non-null     float64
dtypes: float64(2), int64(3)
memory usage: 1.1 KB

In [5]:
df.head(10)

    ano  mes  quantidade_pedidos    faturamento  ticket_medio
0  2016    9                   4     252.239994     84.079998
1  2016   10                 324   59090.479999    182.378025
2  2016   12                   1      19.620001     19.620001
3  2017    1                 800  138488.040064    173.110050
4  2017    2                1780  291908.009507    163.993264
5  2017    3                2682  449863.599528    167.734377
6  2017    4                2404  417788.029499    173.788698
7  2017    5                3700  592918.820136    160.248330
8  2017    6                3245  511276.380329    157.558207
9  2017    7                4026  592382.919487    147.139324

In [6]:
pd.options.display.float_format = '{:,.2f}'.format

In [7]:
df['faturamento'].sum()

np.float64(16008872.120054841)

In [8]:
df.isnull().sum()

ano                   0
mes                   0
quantidade_pedidos    0
faturamento           0
ticket_medio          0
dtype: int64

In [9]:
df.head(10)

    ano  mes  quantidade_pedidos  faturamento  ticket_medio
0  2016    9                   4       252.24         84.08
1  2016   10                 324    59,090.48        182.38
2  2016   12                   1        19.62         19.62
3  2017    1                 800   138,488.04        173.11
4  2017    2                1780   291,908.01        163.99
5  2017    3                2682   449,863.60        167.73
6  2017    4                2404   417,788.03        173.79
7  2017    5                3700   592,918.82        160.25
8  2017    6                3245   511,276.38        157.56
9  2017    7                4026   592,382.92        147.14

In [ ]:
df.to_csv(r"vendas_mensais_tratada.csv", index=False)